# Generated by Django 2.2.7 on 2019-11-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='description',
        ),
    ]
