# Generated by Django 2.2.7 on 2019-11-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_rules_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterModelTable(
            name='roomsamenities',
            table='rooms_amenities',
        ),
        migrations.AlterModelTable(
            name='roomsbeds',
            table='rooms_beds',
        ),
        migrations.AlterModelTable(
            name='roomsrules',
            table='rooms_rules',
        ),
    ]
