# Generated by Django 2.2.7 on 2019-11-16 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('rooms', '0003_auto_20191115_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.HostInfos'),
        ),
    ]
