# Generated by Django 2.2.7 on 2019-11-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_rooms_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='cleaning_fee',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='fee',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
