# Generated by Django 2.2.7 on 2019-11-16 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_image', models.URLField()),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('intro', models.TextField(null=True)),
                ('interaction', models.CharField(max_length=1000, null=True)),
                ('language', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'host_infos',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'social_platform',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('birth_year', models.IntegerField(null=True)),
                ('birth_month', models.IntegerField(null=True)),
                ('birth_day', models.IntegerField(null=True)),
                ('is_host', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.SocialPlatform')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='HostInfosLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.HostInfos')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Languages')),
            ],
            options={
                'db_table': 'host_infos_languages',
            },
        ),
        migrations.AddField(
            model_name='hostinfos',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Users'),
        ),
    ]
