# Generated by Django 2.2.7 on 2019-11-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinfos',
            name='language',
        ),
        migrations.AddField(
            model_name='hostinfos',
            name='language',
            field=models.ManyToManyField(through='account.HostInfosLanguages', to='account.Languages'),
        ),
    ]
