# Generated by Django 2.2.7 on 2019-11-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='check_out',
            field=models.DateField(null=True),
        ),
    ]
