# Generated by Django 2.2.7 on 2019-11-22 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191117_0623'),
        ('reservation', '0002_auto_20191121_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.HostInfos'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='is_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
